contact_links:
  - name: Rebase Suggestions
    url: https://github.com/lilfenfen/Veilbreak-Frontier/discussions
    about: Post suggestions or tweak requests for us to look through while the rebase process is ongoing. This section will be used until we officially rebase.
  - name: Suggestions and Suggestion bounties
    url: https://discord.gg/ZMgPkpEg
    about: Post suggestions for us to apply onto our station, which could be considered for the suggestions bounty system.
